"use client";

import { useEffect, useMemo, useState } from "react";

type Screen = "brief" | "contract" | "alignment" | "strategy" | "bias" | "results";
type StrategyConfig = { primarySource:string; primarySignal:string; operator:string; threshold:number; lookback:number; direction:string; hold:number; secondaryEnabled:boolean; secondarySource:string; secondarySignal:string; secondaryOperator:string; secondaryThreshold:number };
const screens: { id: Screen; label: string; short: string }[] = [
  { id: "brief", label: "Research Brief", short: "01" }, { id: "contract", label: "Data Contract", short: "02" },
  { id: "alignment", label: "Time Alignment", short: "03" }, { id: "strategy", label: "Strategy Builder", short: "04" },
  { id: "bias", label: "Bias Guard", short: "05" }, { id: "results", label: "Results Lab", short: "06" },
];
const blocks = ["Lag", "Z-score", "Regime filter", "Position sizing", "Stop / exit", "Transaction costs"];

export default function Home() {
  const [screen, setScreen] = useState<Screen>("brief");
  const [question, setQuestion] = useState("Does an inflation surprise predict short-term gold returns?");
  const [asset, setAsset] = useState("XAUUSD"); const [macro, setMacro] = useState("US CPI");
  const [horizon, setHorizon] = useState("5 trading days"); const [validated, setValidated] = useState(false);
  const [aligned, setAligned] = useState(false); const [selectedBlocks, setSelectedBlocks] = useState(["Lag", "Z-score", "Regime filter", "Transaction costs"]);
  const [optionalData, setOptionalData] = useState<string[]>(["DXY Index"]);
  const [strategy, setStrategy] = useState<StrategyConfig>({primarySource:"US CPI",primarySignal:"Z-score",operator:">",threshold:1.5,lookback:20,direction:"Long",hold:5,secondaryEnabled:true,secondarySource:"DXY Index",secondarySignal:"Rate of change",secondaryOperator:"<",secondaryThreshold:0});
  const [running, setRunning] = useState(false); const [runComplete, setRunComplete] = useState(false); const [dismissedLeak, setDismissedLeak] = useState(false);
  const [showGuide, setShowGuide] = useState(true); const [toast, setToast] = useState("");
  const readiness = useMemo(() => Math.min(100, 36 + (question.trim().length > 20 ? 12 : 0) + (validated ? 20 : 0) + (aligned ? 16 : 0) + (selectedBlocks.length >= 4 ? 16 : 0)), [question, validated, aligned, selectedBlocks]);
  const completed: Screen[] = ["brief", ...(validated ? ["contract" as Screen] : []), ...(aligned ? ["alignment" as Screen] : []), ...(runComplete ? ["strategy" as Screen, "bias" as Screen] : []), ...(runComplete && dismissedLeak ? ["results" as Screen] : [])];
  useEffect(() => { const seen = window.localStorage.getItem("chronoalpha-guide-seen"); if (seen) setShowGuide(false); }, []);
  function go(next: Screen) { setScreen(next); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function runBacktest() { setRunning(true); setRunComplete(false); go("bias"); window.setTimeout(() => { setRunning(false); setRunComplete(true); }, 1500); }
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2400); }
  function saveDraft() { window.localStorage.setItem("chronoalpha-draft", JSON.stringify({question,asset,macro,horizon,selectedBlocks,optionalData,strategy})); notify("Draft saved on this device"); }
  function closeGuide() { window.localStorage.setItem("chronoalpha-guide-seen", "1"); setShowGuide(false); }
  function resetDemo() { window.localStorage.removeItem("chronoalpha-draft"); setValidated(false); setAligned(false); setRunComplete(false); setDismissedLeak(false); setSelectedBlocks(["Lag", "Z-score", "Regime filter", "Transaction costs"]); go("brief"); notify("Demo reset"); }
  function toggleDataset(name: string) { setOptionalData(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]); setValidated(false); }
  return <main className="app-shell"><aside className="sidebar">
    <button className="brand" onClick={() => go("brief")}><span className="brand-mark">Cα</span><span><b>CHRONOALPHA</b><small>POINT-IN-TIME RESEARCH</small></span></button>
    <div className="project-chip"><span>Inflation & gold</span><small>Active research</small></div>
    <nav>{screens.map(item => <button key={item.id} className={`${screen === item.id ? "active" : ""} ${completed.includes(item.id)?"done":""}`} onClick={() => go(item.id)}><span>{completed.includes(item.id)?"✓":item.short}</span>{item.label}</button>)}</nav>
    <div className="sidebar-footer"><span className="status-dot" />Prototype workspace<small>All changes saved locally</small></div>
  </aside><section className="workspace"><header className="topbar"><div><span>ChronoAlpha</span><b>/</b><strong>{screens.find(s => s.id === screen)?.label}</strong></div><div className="top-actions"><button className="text-button" onClick={() => setShowGuide(true)}>How this works</button><span className="readiness">Readiness <b>{readiness}%</b></span><button className="secondary" onClick={saveDraft}>Save draft</button></div></header><div className="progress-track"><span style={{width:`${readiness}%`}} /></div>
    {screen === "brief" && <ResearchBrief question={question} setQuestion={setQuestion} asset={asset} setAsset={setAsset} macro={macro} setMacro={setMacro} horizon={horizon} setHorizon={setHorizon} readiness={readiness} next={() => go("contract")} />}
    {screen === "contract" && <DataContract asset={asset} macro={macro} optionalData={optionalData} toggleDataset={toggleDataset} validated={validated} validate={() => setTimeout(() => setValidated(true), 500)} next={() => go("alignment")} />}
    {screen === "alignment" && <TimeAlignment macro={macro} aligned={aligned} align={() => setTimeout(() => setAligned(true), 650)} next={() => go("strategy")} />}
    {screen === "strategy" && <StrategyBuilder blocks={blocks} selected={selectedBlocks} setSelected={setSelectedBlocks} asset={asset} datasets={[macro,"HY OAS",...optionalData]} strategy={strategy} setStrategy={setStrategy} run={runBacktest} />}
    {screen === "bias" && <BiasGuard running={running} complete={runComplete} dismissed={dismissedLeak} strategy={strategy} resolve={() => setDismissedLeak(true)} results={() => go("results")} />}
    {screen === "results" && <ResultsLab ready={runComplete && dismissedLeak} strategy={strategy} asset={asset} rerun={() => go("strategy")} />}
  </section>{toast && <div className="toast" role="status"><b>✓</b>{toast}</div>}{showGuide && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="guide-title"><section className="guide-modal"><button className="modal-close" onClick={closeGuide} aria-label="Close guide">×</button><span className="guide-kicker">GUIDED PROTOTYPE · 3 MINUTES</span><h2 id="guide-title">Trust the timeline.<br/>Then trust the strategy.</h2><p>Follow one researcher from a market hypothesis to auditable evidence. The prototype deliberately exposes a timing mistake so you can see how the system prevents false confidence.</p><ol><li><b>Frame</b><span>Define a falsifiable research question</span></li><li><b>Contract</b><span>Declare when each dataset becomes usable</span></li><li><b>Validate</b><span>Detect and repair look-ahead leakage</span></li><li><b>Decide</b><span>Interpret evidence, not just performance</span></li></ol><div className="modal-actions"><button className="secondary" onClick={resetDemo}>Reset demo</button><button className="primary" onClick={closeGuide}>Start guided walkthrough →</button></div><small>No real trades are placed. Results are illustrative for usability testing.</small></section></div>}</main>;
}

function PageIntro({ step, title, description, action }: { step: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-intro"><div><p>{step}</p><h1>{title}</h1><span>{description}</span></div>{action}</div>; }
function Field({ label, value, set, options }: any) { return <label className="field"><span>{label}</span><select value={value} onChange={e => set(e.target.value)}>{options.map((o:string)=><option key={o}>{o}</option>)}</select></label>; }

function ResearchBrief({ question, setQuestion, asset, setAsset, macro, setMacro, horizon, setHorizon, readiness, next }: any) { return <div className="page"><PageIntro step="STEP 01 / FRAME THE RESEARCH" title="Research Brief" description="Turn a broad market idea into a falsifiable, point-in-time question." action={<button className="primary" onClick={next}>Save brief →</button>} /><div className="grid two-one"><section className="panel research-card"><label>RESEARCH QUESTION</label><textarea value={question} onChange={e => setQuestion(e.target.value)} /><label>RESEARCH SUMMARY</label><p>Should the strategy reduce equity exposure when funding stress expands before inflation-sensitive assets reprice?</p><div className="form-grid"><Field label="ASSET" value={asset} set={setAsset} options={["XAUUSD", "SPX", "EURUSD"]}/><Field label="MACRO SERIES" value={macro} set={setMacro} options={["US CPI", "HY OAS", "Funding stress"]}/><Field label="TEST HORIZON" value={horizon} set={setHorizon} options={["1 trading day", "5 trading days", "20 trading days"]}/></div></section><aside className="stack"><section className="panel score-panel"><label>RESEARCH READINESS</label><div className="score-ring" style={{"--score": `${readiness * 3.6}deg`} as React.CSSProperties}><b>{readiness}</b></div><p>{readiness < 70 ? "Define the data contract and timing assumptions next." : "The brief is ready for validation."}</p></section><section className="panel"><label>HOW MIGHT WE?</label><h3>How might we make data availability rules visible before a strategy runs?</h3></section></aside></div></div>; }

function DataContract({ asset, macro, optionalData, toggleDataset, validated, validate, next }: any) { const optional:any = {"DXY Index":["Currency index","Daily","NY close + 15m","READY"],"VIX Index":["Volatility","Daily","CBOE close","READY"],"Fed Funds Rate":["Policy rate","Event","FOMC release time","READY"]}; const rows = [[asset,"Price","1 min","Exchange time","READY"],[macro,"Macro","Monthly","Release timestamp","READY"],["HY OAS","Credit","Daily","End-of-day + 1h","REVIEW"],...optionalData.map((name:string)=>[name,...optional[name]])]; return <div className="page"><PageIntro step="STEP 02 / DEFINE THE EVIDENCE" title="Data Contract" description="Declare what each series means, when it becomes usable, and how it may be transformed." action={<button className="primary" onClick={validate}>{validated ? "Validated ✓" : "Validate contract"}</button>} /><section className="panel optional-datasets"><div><label>OPTIONAL TEST DATASETS</label><p>Add context variables to challenge the original relationship. Changing the evidence invalidates the previous contract.</p></div><div className="dataset-options">{Object.keys(optional).map(name=><button key={name} className={optionalData.includes(name)?"selected":""} onClick={()=>toggleDataset(name)}><span>{optionalData.includes(name)?"✓":"+"}</span><b>{name}</b><small>{optional[name][0]}</small></button>)}</div></section><section className="panel table-panel"><div className="table-head"><span>SERIES</span><span>TYPE</span><span>FREQUENCY</span><span>AVAILABLE AT</span><span>STATUS</span></div>{rows.map((r:any[])=><div className="table-row" key={r[0]}>{r.map((v,j)=><span key={j} className={j===4?`state ${String(v).toLowerCase()}`:""}>{v}</span>)}</div>)}</section><section className={`contract-warning ${validated?"resolved":""}`}><div><b>{validated ? "Contract validated" : "Evidence changed — validation required"}</b><span>{validated ? `${rows.length} sources now have explicit availability rules.` : "Validate release-time and transformation rules before continuing."}</span></div><button className="secondary" onClick={validated?next:validate}>{validated ? "Continue →" : "Validate evidence"}</button></section></div>; }

function TimeAlignment({ macro, aligned, align, next }: any) { return <div className="page"><PageIntro step="STEP 03 / ALIGN AVAILABILITY" title="Time Alignment" description="Inspect the event clock before a backtest joins macro observations to market bars." action={<button className="primary" onClick={align}>{aligned ? "Alignment complete ✓" : "Run alignment"}</button>} /><section className="panel timeline-panel"><div className="timeline-meta"><div><label>EVENT</label><b>{macro} release</b></div><div><label>POLICY</label><b>First tradable bar after release</b></div><div><label>TIMEZONE</label><b>UTC normalized</b></div></div><div className="timeline-chart"><div className="axis"/><div className="event obs"><span>Observed</span><i>08:30</i></div><div className="event release"><span>Released</span><i>12:30</i></div><div className="event trade"><span>Tradable</span><i>12:31</i></div><div className={`alignment-path ${aligned?"shown":""}`} /></div><div className="legend"><span><i className="obs-dot"/>Observation</span><span><i className="release-dot"/>Release</span><span><i className="trade-dot"/>First usable bar</span></div></section><div className="insight-row"><section className="panel"><label>RISK</label><h3>Same-date joins are deceptive.</h3><p>A value published after the market closes cannot influence that day’s return.</p></section><section className="panel"><label>RULE</label><h3>{aligned ? "No future timestamp detected" : "Awaiting alignment run"}</h3><p>Only released values may move forward into later price bars.</p></section><button className="next-card" disabled={!aligned} onClick={next}>Build strategy <b>→</b></button></div></div>; }

function StrategyBuilder({ blocks, selected, setSelected, asset, datasets, strategy, setStrategy, run }: any) {
  const toggle=(b:string)=>setSelected((x:string[])=>x.includes(b)?x.filter(v=>v!==b):[...x,b]);
  const update=(key:string,value:any)=>setStrategy((current:StrategyConfig)=>({...current,[key]:value}));
  const signals=["Z-score","Rate of change","Percentile rank","Release surprise","Moving-average spread"];
  return <div className="page"><PageIntro step="STEP 04 / DESIGN THE LOGIC" title="Strategy Builder" description="Connect datasets and tune every rule. The downstream audit will test this exact configuration." action={<button className="primary" onClick={run}>Run configured test →</button>} />
    <section className="strategy-summary"><span>IF</span><b>{strategy.primarySource} · {strategy.primarySignal} {strategy.operator} {strategy.threshold}</b>{strategy.secondaryEnabled&&<><span>AND</span><b>{strategy.secondarySource} · {strategy.secondarySignal} {strategy.secondaryOperator} {strategy.secondaryThreshold}</b></>}<span>THEN</span><b>{strategy.direction} {asset} for {strategy.hold} days</b></section>
    <div className="composer-grid"><section className="panel rule-editor"><div className="rule-title"><span>01</span><div><label>PRIMARY SIGNAL</label><p>The condition that creates an entry.</p></div></div><div className="control-grid"><ConfigSelect label="DATASET" value={strategy.primarySource} set={(v:string)=>update("primarySource",v)} options={datasets}/><ConfigSelect label="TRANSFORMATION" value={strategy.primarySignal} set={(v:string)=>update("primarySignal",v)} options={signals}/><ConfigSelect label="OPERATOR" value={strategy.operator} set={(v:string)=>update("operator",v)} options={[">","<",">=","<="]}/><ConfigNumber label="THRESHOLD" value={strategy.threshold} set={(v:number)=>update("threshold",v)} step="0.1"/><ConfigNumber label="LOOKBACK" value={strategy.lookback} set={(v:number)=>update("lookback",v)} step="1" suffix="releases"/></div>
      <div className="rule-divider"/><div className="rule-title"><button className={`toggle ${strategy.secondaryEnabled?"on":""}`} onClick={()=>update("secondaryEnabled",!strategy.secondaryEnabled)} aria-label="Toggle confirmation signal"><i/></button><div><label>CONFIRMATION SIGNAL</label><p>Optional evidence that must agree before entry.</p></div></div>{strategy.secondaryEnabled&&<div className="control-grid secondary-controls"><ConfigSelect label="DATASET" value={datasets.includes(strategy.secondarySource)?strategy.secondarySource:datasets[0]} set={(v:string)=>update("secondarySource",v)} options={datasets}/><ConfigSelect label="TRANSFORMATION" value={strategy.secondarySignal} set={(v:string)=>update("secondarySignal",v)} options={signals}/><ConfigSelect label="OPERATOR" value={strategy.secondaryOperator} set={(v:string)=>update("secondaryOperator",v)} options={[">","<",">=","<="]}/><ConfigNumber label="THRESHOLD" value={strategy.secondaryThreshold} set={(v:number)=>update("secondaryThreshold",v)} step="0.1"/></div>}</section>
      <aside className="stack"><section className="panel execution-panel"><label>POSITION & EXIT</label><ConfigSelect label="DIRECTION" value={strategy.direction} set={(v:string)=>update("direction",v)} options={["Long","Short","Long / Short"]}/><ConfigNumber label="HOLDING PERIOD" value={strategy.hold} set={(v:number)=>update("hold",v)} step="1" suffix="days"/><div className="execution-note"><span>Target</span><b>{asset}</b><span>Execution</span><b>Next tradable bar</b></div></section><section className="panel compact-library"><label>SAFETY BLOCKS</label>{blocks.map((b:string)=><button key={b} className={selected.includes(b)?"selected":""} onClick={()=>toggle(b)}><span>{selected.includes(b)?"✓":"+"}</span>{b}</button>)}</section></aside>
    </div><section className="panel flow-preview"><label>LIVE LOGIC MAP</label><div className="flow-row"><div><small>SOURCE</small><b>{strategy.primarySource}</b></div><i>→</i><div><small>TRANSFORM</small><b>{strategy.lookback}-release {strategy.primarySignal}</b></div><i>→</i>{strategy.secondaryEnabled&&<><div><small>CONFIRM</small><b>{strategy.secondarySource}</b></div><i>→</i></>}<div><small>TRADE</small><b>{strategy.direction} {asset}</b></div><i>→</i><div><small>EXIT</small><b>{strategy.hold} days</b></div></div></section>
  </div>;
}

function ConfigSelect({label,value,set,options}:any){return <label className="config-field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map((o:string)=><option key={o} value={o}>{o}</option>)}</select></label>}
function ConfigNumber({label,value,set,step,suffix}:any){return <label className="config-field"><span>{label}</span><div className="number-wrap"><input type="number" min="0" step={step} value={value} onChange={e=>set(Number(e.target.value))}/>{suffix&&<em>{suffix}</em>}</div></label>}

function BiasGuard({ running, complete, dismissed, strategy, resolve, results }: any) { const checks=[["Look-ahead leakage",`${strategy.primarySource} checked against first-publication timestamp`,dismissed?"PASS":"CRITICAL"],["Connected-data lineage",strategy.secondaryEnabled?`${strategy.secondarySource} joins traced to the decision bar`:"No confirmation dataset connected","PASS"],["Parameter declaration",`${strategy.primarySignal}, ${strategy.lookback}-release lookback, threshold ${strategy.threshold}`,"PASS"],["Execution timing",`${strategy.direction} entry delayed to next tradable bar`,"PASS"],["Missing-data policy","Forward-fill capped at 31 days","REVIEW"]]; return <div className="page"><PageIntro step="STEP 05 / PROTECT INTEGRITY" title="Bias Guard" description="The audit now reflects every dataset, transformation and value selected in Strategy Builder." />{running && <section className="scanning"><span/><b>Replaying {strategy.primarySource}{strategy.secondaryEnabled?` + ${strategy.secondarySource}`:""} through historical timestamps…</b></section>}{!running && <div className="grid two-one"><section className="panel"><div className={`guard-banner ${dismissed?"pass":"blocked"}`}><b>{dismissed?"CLEARED":"BLOCKED"}</b><span>{dismissed?"The configured strategy is reproducible and time-valid.":"1 critical release-time failure blocks these results."}</span></div>{checks.map(([a,b,c])=><div className="check-row" key={a}><div><b>{a}</b><span>{b}</span></div><em className={`state ${c.toLowerCase()}`}>{c}</em></div>)}</section><aside className="panel review-card"><label>CONFIGURATION UNDER REVIEW</label><h2>{strategy.primarySource} {strategy.primarySignal}</h2><p>{strategy.direction} when the {strategy.lookback}-release signal is {strategy.operator} {strategy.threshold}{strategy.secondaryEnabled?`, confirmed by ${strategy.secondarySource}`:""}.</p><div className="compare"><span><small>Naive Sharpe</small><b>1.84</b></span><span><small>Point-in-time</small><b>1.31</b></span></div>{!dismissed?<button className="primary full" onClick={resolve}>Apply release-time fix</button>:<button className="primary full" disabled={!complete} onClick={results}>Open results →</button>}</aside></div>}</div>; }

function ResultsLab({ ready, strategy, asset, rerun }: any) { const strength=Math.max(.72,1.31+(strategy.secondaryEnabled?.12:0)-(Math.abs(strategy.threshold-1.5)*.08)); const survival=Math.max(42,68+(strategy.lookback===20?6:0)+(strategy.secondaryEnabled?5:0)); return <div className="page"><PageIntro step="STEP 06 / INTERPRET EVIDENCE" title="Results Lab" description={`${strategy.direction} ${asset} · ${strategy.primarySource} ${strategy.primarySignal} ${strategy.operator} ${strategy.threshold} · ${strategy.hold}-day hold`} action={<button className="secondary" onClick={rerun}>Edit this strategy</button>} />{!ready && <section className="empty-state"><span>!</span><h2>Bias review is incomplete</h2><p>Resolve critical data-timing risks before results can be promoted.</p></section>}{ready && <><section className="result-definition"><span>TESTED LOGIC</span><b>{strategy.primarySource} {strategy.primarySignal} {strategy.operator} {strategy.threshold}</b>{strategy.secondaryEnabled&&<><i>+</i><b>{strategy.secondarySource} confirmation</b></>}<i>→</i><b>{strategy.direction} {asset}</b></section><div className="metrics"><Metric label="OOS SHARPE" value={strength.toFixed(2)} tone="lime"/><Metric label="MAX DRAWDOWN" value={`−${(13.1+strategy.hold*.22).toFixed(1)}%`}/><Metric label="COST MULTIPLE" value={strategy.hold<=5?"2.3×":"2.7×"} tone="cyan"/><Metric label="PARAMETER SURVIVAL" value={`${survival}%`} tone="lime"/></div><div className="results-grid"><section className="panel chart-card"><label>EQUITY CURVE · OUT OF SAMPLE</label><div className="equity"><div className="gridlines"/><div className="equity-line"/><div className="benchmark-line"/></div><div className="chart-legend"><span><i/>Configured strategy</span><span><i/>Benchmark</span></div></section><aside className="panel decision"><label>DECISION</label><h2>{survival>=75?"ITERATE":"REWORK"}</h2><p>The signal remains positive after timing correction, but neighbouring thresholds still require review.</p><ul><li><span>Primary source</span><b>{strategy.primarySource}</b></li><li><span>Confirmation</span><b>{strategy.secondaryEnabled?strategy.secondarySource:"None"}</b></li><li><span>Holding period</span><b>{strategy.hold} days</b></li></ul><button className="primary full" onClick={rerun}>Adjust parameters</button></aside></div></>}</div>; }
function Metric({label,value,tone=""}:any){return <section className="panel metric"><label>{label}</label><b className={tone}>{value}</b></section>}
